# Generated by Django 5.1.6 on 2025-03-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("first_name", models.CharField(blank=True, max_length=512, null=True)),
                ("last_name", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
