# Generated by Django 5.1.6 on 2025-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_usertransaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapiusage",
            name="total_limit",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
