# Generated by Django 5.1.6 on 2025-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_userapiusage_total_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapiusage",
            name="remaining_limit",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
