# Generated by Django 5.1.6 on 2025-03-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_userapiusage_remaining_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
