# Generated by Django 5.1.6 on 2025-03-06 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monthly_price', models.IntegerField(default=0)),
                ('yearly_price', models.IntegerField(default=0)),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('package', models.CharField(choices=[('MonthlyPro', 'MonthlyPro'), ('MonthlyPro50', 'MonthlyPro50'), ('MonthlyPro100', 'MonthlyPro100'), ('MonthlyPro200', 'MonthlyPro200'), ('YearlyPro', 'YearlyPro'), ('YearlyPro50', 'YearlyPro50'), ('YearlyPro100', 'YearlyPro100'), ('YearlyPro200', 'YearlyPro200')], default='MonthlyPro', max_length=25)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('cancel_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_in_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=0)),
                ('charge_id', models.CharField(blank=True, max_length=256, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction History',
                'verbose_name_plural': 'transactions History',
            },
        ),
    ]
